'use client'

import React from "react";
import Header from "@/components/ui/Header";
import Footer from "@/components/ui/Footer";
import { Shield, ShieldCheck, CheckCircle } from "lucide-react";
import { motion } from "framer-motion";
import { Separator } from "@/components/ui/separator";
import Link from "next/link";

const Terms = () => {
  const termsData = [
    {
      title: "Terms of Service",
      content: [
        "By using NativeCraft, you agree to comply with and be bound by these Terms of Service. If you do not agree with any part of these terms, you must not use our service.",
        "NativeCraft provides a platform for generating mobile and web application templates. Users can input an app name and bundle ID, and our system will generate a zip folder containing corresponding code and files for download. The service is intended for developers and those with technical knowledge.",
        "You are responsible for the content you generate using our service. You must ensure that your use of our platform complies with all applicable laws and regulations.",
        "You agree not to use our service for any unlawful or harmful purpose, including but not limited to generating malicious code or infringing on intellectual property rights.",
        "The code and templates generated by NativeCraft are provided for your use. You retain ownership of the apps you create. However, NativeCraft retains ownership of the underlying platform and its intellectual property.",
        "You agree not to reproduce, distribute, or create derivative works from our platform without our express written permission.",
        "NativeCraft is provided \"as is\" without any warranties, express or implied. We do not warrant that our service will be error-free or uninterrupted.",
        "We disclaim all warranties of merchantability and fitness for a particular purpose.",
        "In no event shall NativeCraft be liable for any direct, indirect, incidental, special, or consequential damages arising out of or in connection with your use of our service.",
        "We reserve the right to modify these Terms of Service at any time. We will notify you of any changes by posting the new terms on our website. Your continued use of the service after such changes constitutes your acceptance of the new terms.",
        "These Terms of Service shall be governed by and construed in accordance with the laws of the United States."
      ]
    },
    {
      title: "Privacy Policy",
      content: [
        "When you use NativeCraft, we collect the app name and bundle ID you provide to generate your application template. We also use Firebase to track events and usage patterns, which may include anonymous data about how you interact with our service.",
        "We do not collect any personally identifiable information (PII) such as names, email addresses, or IP addresses, unless you provide them to us directly for support purposes.",
        "We use the app name and bundle ID to generate the zip folder you requested. We use Firebase data to analyze usage patterns, improve our service, and troubleshoot any issues.",
        "We do not sell or share your information with third parties, except as required by law or to provide our service (e.g., Firebase for event tracking).",
        "We take reasonable measures to protect the information we collect from unauthorized access, use, or disclosure.",
        "However, no method of transmission over the Internet or electronic storage is 100% secure.",
        "Firebase may use cookies or similar technologies to track events and usage data. You can control cookies through your browser settings.",
        "Our service may contain links to third-party websites. We are not responsible for the privacy practices of these websites.",
        "Our service is not intended for children under the age of 13. We do not knowingly collect personal information from children.",
        "We reserve the right to modify this Privacy Policy at any time. We will notify you of any changes by posting the new policy on our website."
      ]
    },
    {
      title: "Contact Information",
      content: [
        "If you have any questions about these terms or policies, please contact us at support@nativecraft.com."
      ]
    }
  ];

  return (
    <div className="min-h-screen flex flex-col">

      
      <main className="flex-1 container mx-auto py-12 px-4">
        <motion.div 
          className="mb-12 text-center"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <div className="flex justify-center mb-4">
            <div className="relative">
              <Shield className="h-12 w-12 text-primary" />
              <ShieldCheck className="h-6 w-6 absolute -bottom-1 -right-1 text-green-500" />
            </div>
          </div>
          <h1 className="text-4xl font-bold mb-4">Terms & Policies</h1>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Please review our terms of service, privacy policy, and other legal agreements.
          </p>
        </motion.div>

        <div className="max-w-4xl mx-auto bg-background/50 backdrop-blur-sm rounded-xl p-8 shadow-sm">
          <div className="space-y-10">
            {termsData.map((section, index) => (
              <motion.div 
                key={section.title}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
              >
                <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
                  <CheckCircle className="h-5 w-5 text-primary" />
                  {section.title}
                </h2>
                <Separator className="mb-4" />
                <div className="space-y-4">
                  {section.content.map((paragraph, i) => (
                    <p key={i} className="text-muted-foreground">
                      {paragraph}
                    </p>
                  ))}
                </div>
                {index < termsData.length - 1 && (
                  <div className="h-8" />
                )}
              </motion.div>
            ))}
          </div>

          <motion.div 
            className="mt-10 text-center"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.5, delay: 0.5 }}
          >
            <p className="text-sm text-muted-foreground mb-4">
              Last updated: April 4, 2025
            </p>
            <div className="flex flex-wrap justify-center gap-4">
              <Link href="/" className="text-sm text-primary hover:underline">
                Return to Home
              </Link>
              <Link href="/documentation" className="text-sm text-primary hover:underline">
                View Documentation
              </Link>
              <a href="mailto:support@nativecraft.com" className="text-sm text-primary hover:underline">
                Contact Support
              </a>
            </div>
          </motion.div>
        </div>
      </main>
      
    </div>
  );
};

export default Terms;